"""Builds the tool: one self-contained HTML file from src/.

    python build.py            write index.html, the page, at the root of the source folder
    python build.py <path>     write it somewhere else

Everything the page holds comes from src/: the modules in src/js, the style, the body, the fonts, the shipped
buildings, and the folder links setup. Two modules are made here in memory and never written to disk:
25-generics.js (the buildings and lots in src/buildings) and 26-extra.js (the version and the setup script)."""
import base64, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent              # the source folder, wherever it is unpacked
SRC = ROOT / 'src'
F = SRC / 'fonts'
OUT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'index.html'      # the repo keeps it, and GitHub Pages serves it

def write(path, text):
    """Writes UTF-8 with LF line ends on every OS, so a build on Windows matches a build anywhere else."""
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)

LATIN = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
LATIN_EXT = 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
ARABIC = 'U+0600-06FF,U+0750-077F,U+0870-088E,U+0890-0891,U+0897-08E1,U+08E3-08FF,U+200C-200E,U+2010-2011,U+204F,U+2E41,U+FB50-FDFF,U+FE70-FE74,U+FE76-FEFC'

def face(family, weight, path, urange):
    data = base64.b64encode(path.read_bytes()).decode()
    return (f"@font-face{{font-family:'{family}';font-style:normal;font-display:swap;font-weight:{weight};"
            f"src:url(data:font/woff2;base64,{data}) format('woff2');unicode-range:{urange};}}\n")

px = F / 'pixelify-sans'
rx = F / 'readex-pro'
fonts = ''.join([
    face('Pixelify Sans', '400 700', px / 'pixelify-sans-latin-wght-normal.woff2', LATIN),
    face('Pixelify Sans', '400 700', px / 'pixelify-sans-latin-ext-wght-normal.woff2', LATIN_EXT),
    face('Readex Pro', '160 700', rx / 'readex-pro-arabic-wght-normal.woff2', ARABIC),
    face('Readex Pro', '160 700', rx / 'readex-pro-latin-wght-normal.woff2', LATIN),
    face('Readex Pro', '160 700', rx / 'readex-pro-latin-ext-wght-normal.woff2', LATIN_EXT),
])

import json
art_out = SRC / 'buildings'
meta = json.loads((art_out / 'meta.json').read_text(encoding='utf-8'))
gen = ['/* Generated by build.py from src/buildings: the generic buildings, drawn in code. */', 'const GENERICS = [']
for m in meta:
    data = base64.b64encode((art_out / (m['id'] + '.gif')).read_bytes()).decode()
    gen.append("  { id: %s, name: %s, footprint: %s, url: 'data:image/gif;base64,%s' }," % (json.dumps(m['id']), json.dumps(m['title']), json.dumps(m['footprint']), data))
gen.append('];')
gen.append('const GENERIC_IDS = new Set(GENERICS.map(g => g.id));')
lots = json.loads((art_out / 'lots.json').read_text(encoding='utf-8'))
gen.append('/* Empty lots: little scenes, one picked per lot by its position. */')
gen.append('const LOTS = [')
for l in lots:
    data = base64.b64encode((art_out / ('lot-' + l['id'] + '.gif')).read_bytes()).decode()
    gen.append("  { id: %s, url: 'data:image/gif;base64,%s' }," % (json.dumps(l['id']), data))
gen.append('];')
props = json.loads((art_out / 'props.json').read_text(encoding='utf-8'))
gen.append('/* Street props: a front and a back each, at double detail like the buildings. faces: the street the front faces as')
gen.append('   drawn, south-east or south-west; the back faces the opposite street, the same diagonal turned around. */')
gen.append('const PROPS = [')
for pr in props:
    if pr.get('faces') not in ('se', 'sw'):           # a wrong guess turns the prop sideways on every block side
        sys.exit('src/buildings/props.json: %s needs "faces", the street its front faces as drawn: "se" or "sw"' % pr['id'])
    urls = {s: base64.b64encode((art_out / ('prop-%s-%s.png' % (pr['id'], s))).read_bytes()).decode() for s in ('front', 'back')}
    gen.append("  { id: %s, faces: %s, front: 'data:image/png;base64,%s', back: 'data:image/png;base64,%s' }," % (json.dumps(pr['id']), json.dumps(pr['faces']), urls['front'], urls['back']))
gen.append('];')
GENERATED = {'25-generics.js': '\n'.join(gen) + '\n'}
# the Windows setup for folder links: one source file, embedded as text so the tool can hand out the same file
setup = (SRC / 'setup' / 'nullovation-folder-links.ps1').read_text(encoding='utf-8')
VERSION = (SRC / 'VERSION').read_text(encoding='utf-8').strip()               # one source for the version: bump it with every fix or UI change
GENERATED['26-extra.js'] = '/* Generated by build.py from src/setup and src/VERSION. */\nconst APP_VERSION = ' + json.dumps(VERSION) + ';\nconst FOLDER_SETUP_PS1 = ' + json.dumps(setup) + ';\n'

css = (SRC / 'style.css').read_text(encoding='utf-8')
body = (SRC / 'body.html').read_text(encoding='utf-8').replace('{{VERSION}}', VERSION)
# the modules in name order, with the two made above in their places; a leftover copy of one on disk is ignored
modules = {p.name: p.read_text(encoding='utf-8') for p in (SRC / 'js').glob('*.js')}
for name in sorted(set(modules) & set(GENERATED)):
    print(f'note: ignoring src/js/{name}, left over from before 0.1.17; the build makes it in memory')
modules.update(GENERATED)
js = '\n'.join(modules[name] for name in sorted(modules))

favicon = ("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' shape-rendering='crispEdges'%3E"
           "%3Crect x='2' y='5' width='5' height='11' fill='%23F4A3C3'/%3E%3Crect x='8' y='1' width='6' height='15' fill='%237FD6CE'/%3E"
           "%3Crect x='3' y='7' width='1' height='2' fill='%232B2542'/%3E%3Crect x='5' y='7' width='1' height='2' fill='%232B2542'/%3E"
           "%3Crect x='10' y='3' width='2' height='2' fill='%232B2542'/%3E%3Crect x='10' y='7' width='2' height='2' fill='%232B2542'/%3E"
           "%3Crect x='10' y='11' width='2' height='2' fill='%23FFEBA0'/%3E%3C/svg%3E")

html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nullovation City</title>
<link rel="icon" href="{favicon}">
<style>
{fonts}
{css}
</style>
</head>
<body>
{body}
<script>
{js}
</script>
</body>
</html>
"""

bad = [c for c in ('\u2014', '\u2013') if c in html]
if bad:
    for m in re.finditer('[\u2014\u2013]', html):
        print('DASH at', m.start(), repr(html[max(0, m.start() - 40):m.start() + 40]))
    sys.exit('em or en dash found; fix before shipping')

OUT.parent.mkdir(parents=True, exist_ok=True)
write(OUT, html)
print(f'built {OUT} ({len(html) / 1024:.0f} KB)')
