import pathlib
from playwright.sync_api import sync_playwright
from testkit import FILE, ROOT, SHOTS, SH, DATA, SKILLS, VERSION, fixture, TEST_CITY

errors = []
def ok(label, cond): print(('PASS ' if cond else 'FAIL ') + label)

with sync_playwright() as p:
    b = p.chromium.launch(channel='chrome')
    ctx = b.new_context(viewport={'width': 1440, 'height': 900}, device_scale_factor=1)
    ctx.add_init_script(TEST_CITY)
    ctx.grant_permissions(['clipboard-read', 'clipboard-write'])
    pg = ctx.new_page()
    pg.on('pageerror', lambda e: errors.append(str(e))); pg.on('console', lambda m: errors.append(m.text) if m.type in ('error', 'warning') else None)
    pg.goto(FILE); pg.wait_for_timeout(2200)
    left = pg.evaluate("() => document.querySelector('#mapWrap').getBoundingClientRect().left")
    wz = pg.evaluate("() => DB.projects.find(p => p.name.startsWith('Garden')).id")
    proj = lambda: pg.evaluate(f"() => JSON.parse(JSON.stringify(DB.projects.find(p => p.id === '{wz}')))")
    clip = lambda: pg.evaluate("() => navigator.clipboard.readText()")

    # 7: the bubble: no what-is-next line, a copy per task, and Copy status
    pg.evaluate("() => MapView.setCam({ x: 0, y: 230, z: 2 })"); pg.wait_for_timeout(250)
    a = pg.evaluate(f"() => MapView.anchors('{wz}')")
    pg.mouse.click(left + a['topX'], (a['topY'] + a['baseY']) / 2); pg.wait_for_timeout(500)
    ok('7.1 the bubble no longer carries a what-is-next line', pg.locator('#bubble .b-now').count() == 0)
    n_rows = pg.locator('#bubble .b-todos li').count()
    ok(f'7.2 every task in the bubble has its own copy button ({n_rows})', n_rows > 0 and pg.locator('#bubble .b-todos li .b-copy').count() == n_rows)
    pg.click('#bubble .b-status'); pg.wait_for_timeout(150)
    ok('7.3 the bubble copies the full status', clip().startswith('## Garden planner') and 'Next task: ' in clip())
    row = pg.query_selector('#bubble .b-todos li >> nth=0').bounding_box()
    cp = pg.query_selector('#bubble .b-todos li >> nth=0 >> .b-copy').bounding_box()
    cbx = pg.query_selector('#bubble .b-todos li >> nth=0 >> .cb').bounding_box()
    ok('the copy button sits on the task’s own line, at the end', abs(cp['y'] - cbx['y']) < 8 and cp['x'] > row['x'] + row['width'] - cp['width'] - 4)
    bw = pg.query_selector('#bubble').bounding_box()['width']
    ok(f'the bubble stays compact ({bw:.0f} px wide)', bw <= 340)
    first_id = pg.get_attribute('#bubble .b-todos li >> nth=0', 'data-id')
    pg.click('#bubble .b-todos li >> nth=0 >> .b-task'); pg.wait_for_timeout(600)
    ok('clicking a task’s text in the bubble does not tick it', pg.evaluate(f"() => DB.projects.find(p => p.id === '{wz}').todos.find(t => t.id === '{first_id}').done") is False)
    ok('it opens the project view with that task beside it', pg.is_visible('#pv') and pg.is_visible('#pvSide #pvTaskDesc') and pg.get_attribute('.task.on', 'data-id') == first_id)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200); pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    pg.evaluate("() => MapView.setCam({ x: 0, y: 230, z: 2 })"); pg.wait_for_timeout(250)
    a = pg.evaluate(f"() => MapView.anchors('{wz}')")
    pg.mouse.click(left + a['topX'], (a['topY'] + a['baseY']) / 2); pg.wait_for_timeout(500)

    pg.click('#enterBtn'); pg.wait_for_timeout(700)
    # 5 and 6.6: every task lives in a milestone, counts read (done/total)
    ok('5 no todo exists outside a milestone', all(t['milestoneId'] in [m['id'] for m in proj()['milestones']] for t in proj()['todos']))
    ok('5 nothing on the page adds a task without a milestone', pg.locator('#pvAddTodoBtn, #pvAddTodo').count() == 0 and pg.locator('.ms-plus').count() == len(proj()['milestones']))
    counts = pg.eval_on_selector_all('.ms-row .ms-count', 'els => els.map(e => e.textContent)')
    ok(f'6.6 counts read (done/total) {counts}', counts == ['(0/4)', '(0/1)'])
    # 6.2: collapse, remembered; drag a milestone by its flag
    pg.click('.ms >> nth=1 >> .ms-toggle'); pg.wait_for_timeout(150)
    ok('6.2 a milestone collapses, and it is remembered', not pg.is_visible('.ms >> nth=1 >> ul.tasks') and proj()['milestones'][1]['collapsed'] is True)
    pg.evaluate("() => { const m = document.querySelector('#pv'); m.scrollTop = document.querySelector('.ms-list').offsetTop - 260; }"); pg.wait_for_timeout(150)
    flag = pg.query_selector('.ms >> nth=1 >> .ms-grip').bounding_box()
    first = pg.query_selector('.ms >> nth=0 >> .ms-row').bounding_box()
    pg.mouse.move(flag['x'] + 7, flag['y'] + 7); pg.mouse.down()
    pg.mouse.move(flag['x'] + 7, first['y'] + 2, steps=12); pg.mouse.up(); pg.wait_for_timeout(250)
    ok('6.2 a milestone drags by its flag', [m['name'] for m in proj()['milestones']] == ['Launch', 'First release'])
    ok('6.2 its tasks travel with it, and list order follows', pg.evaluate(f"() => {{ const p = DB.projects.find(p => p.id === '{wz}'); return JSON.stringify(groupsOf(p).flatMap(g => g.todos.map(t => t.id))) === JSON.stringify(p.todos.map(t => t.id)); }}"))
    ok('2 What is next follows the new order', 'Publish the app' in pg.text_content('#pvNextTask'))
    ok('2 What is next is not a field and is not stored', pg.locator('.pv-next input, .pv-next textarea').count() == 0 and 'currentlyAt' not in proj())
    # 6.3 and 6.7: a task opens beside the view; description, due date, copy for Claude, Esc undoes
    pg.click('.ms >> nth=1 >> li.task >> nth=0 >> .task-title'); pg.wait_for_timeout(250)
    pg.fill('#pvTaskDesc', 'Draw each bed to scale and label it.')
    pg.click('#pvSide >> text=Copy task'); pg.wait_for_timeout(150)
    c = clip()
    ok('6.7 Copy task copies the task with its description, and no longer the project\'s About', c.startswith('# Task: Draw the beds') and 'Draw each bed to scale' in c and '## About the project' not in c)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    ok('6.3 Esc in the task undoes its session', proj()['todos'][1]['description'] == '' if proj()['todos'][1]['text'].startswith('Draw the beds') else any(t['text'].startswith('Draw the beds') and t['description'] == '' for t in proj()['todos']))
    # milestone panel: rename, then delete with its tasks after a confirm
    pg.click('.ms >> nth=0 >> .ms-name-btn'); pg.wait_for_timeout(250)
    pg.fill('#pvMsName', 'Rename done'); pg.keyboard.press('Enter'); pg.wait_for_timeout(250)
    ok('clicking a milestone name opens it; Enter keeps the rename', proj()['milestones'][0]['name'] == 'Rename done' and not pg.is_visible('#pvSide'))
    pg.click('.ms >> nth=0 >> .ms-name-btn'); pg.wait_for_timeout(250)
    pg.click('#pvSide >> text=Delete milestone'); pg.wait_for_timeout(200)
    ok('deleting a milestone with tasks asks first', pg.is_visible('.backdrop.top'))
    pg.click('.confirm-actions .btn-danger'); pg.wait_for_timeout(300)
    ok('then the milestone and its task are gone', [m['name'] for m in proj()['milestones']] == ['First release'] and not any(t['text'].startswith('Publish the app') for t in proj()['todos']))
    # 1: the add-link form picks icons on the spot
    pg.click('#pvAddLinkBtn'); pg.fill('#pvLinkUrl', 'https://github.com/team/issue-1'); pg.wait_for_timeout(100)
    ok('1 the icon follows the address as you type', 'GitHub' in pg.get_attribute('#pvLinkIcon', 'aria-label'))
    pg.click('#pvLinkIcon'); pg.click('.icon-pop button[aria-label="Chat"]'); pg.wait_for_timeout(100)
    pg.fill('.pv-add-link input[aria-label="New link label"]', 'Team thread'); pg.keyboard.press('Enter'); pg.wait_for_timeout(200)
    ok('1 the picked icon is kept, with no edit mode', proj()['links'][-1]['icon'] == 'chat' and pg.locator('[data-sec="links"] .pv-done').count() == 0)
    pg.reload(); pg.wait_for_timeout(1800)
    ok('descriptions, collapse state, and order survive a reload', pg.evaluate(f"() => {{ const p = DB.projects.find(p => p.id === '{wz}'); return p.milestones.length === 1 && p.todos.every(t => typeof t.description === 'string'); }}"))
    b.close()
print(errors or 'no console errors')
