import json, pathlib
from playwright.sync_api import sync_playwright
from testkit import FILE, ROOT, SHOTS, SH, DATA, SKILLS, VERSION, fixture, TEST_CITY

PLAN = SKILLS / 'nullovation-city' / 'references' / 'example-plan.json'
errors = []
def ok(label, cond): print(('PASS ' if cond else 'FAIL ') + label)

with sync_playwright() as p:
    b = p.chromium.launch(channel='chrome')
    ctx = b.new_context(viewport={'width': 1440, 'height': 900}, device_scale_factor=1, accept_downloads=True)
    ctx.add_init_script(TEST_CITY)
    ctx.grant_permissions(['clipboard-read', 'clipboard-write'])
    pg = ctx.new_page()
    pg.on('pageerror', lambda e: errors.append(str(e))); pg.on('console', lambda m: errors.append(m.text) if m.type in ('error', 'warning') else None)
    pg.goto(FILE); pg.wait_for_timeout(2200)
    js = lambda code: pg.evaluate(code)
    left = js("() => document.querySelector('#mapWrap').getBoundingClientRect().left")
    wz = js("() => DB.projects.find(p => p.name.startsWith('Garden')).id")
    proj = lambda: js(f"() => JSON.parse(JSON.stringify(DB.projects.find(p => p.id === '{wz}')))")
    js(f"() => {{ const p = DB.projects.find(p => p.id === '{wz}'); p.notes.push({{ id: uid('n'), title: 'Leader', text: 'Captain Mira.', at: Date.now() }}); p.urgency.system = 'finish'; p.urgency.pickedAt = Date.now(); changed(p); }}")
    before = proj()

    def open_view():
        js("() => MapView.setCam({ x: 0, y: 230, z: 2 })"); pg.wait_for_timeout(250)
        a = js(f"() => MapView.anchors('{wz}')")
        pg.mouse.click(left + a['topX'], (a['topY'] + a['baseY']) / 2); pg.wait_for_timeout(450)
        pg.click('#enterBtn'); pg.wait_for_timeout(600)

    open_view()
    pg.click('#pvMore'); pg.wait_for_timeout(100)
    ok('the more menu offers Load plan or tasks', 'Load plan or tasks' in pg.eval_on_selector_all('.pv-menu-item', 'els => els.map(e => e.textContent)'))
    pg.click('.pv-menu-item >> text=Load plan or tasks'); pg.wait_for_timeout(300)
    ok('it opens a dialog with a file button and a paste box, and no change yet', pg.is_visible('.modal.panel #planText') and pg.locator('.modal.panel >> text=Choose the file').count() == 1 and proj()['todos'] == before['todos'])
    ok('Load stays disabled until there is something to load', js("() => document.querySelector('#planLoad').disabled"))
    # bad input is refused with a reason, and nothing changes
    pg.fill('#planText', '{ this is not json'); pg.click('#planLoad'); pg.wait_for_timeout(200)
    ok('bad JSON is refused with a reason', pg.is_visible('.plan-err') and 'not valid JSON' in pg.text_content('.plan-err') and not pg.is_visible('.backdrop.top'))
    pg.fill('#planText', json.dumps({'app': 'nullovation-city', 'kind': 'plan', 'version': 1, 'project': {'description': 'x', 'milestones': []}})); pg.click('#planLoad'); pg.wait_for_timeout(200)
    ok('a plan with no milestones is refused', 'no milestones' in pg.text_content('.plan-err') and proj()['todos'] == before['todos'])
    # the real plan: the warning says what changes, and cancel changes nothing
    pg.fill('#planText', PLAN.read_text()); pg.click('#planLoad'); pg.wait_for_timeout(300)
    body = pg.text_content('.backdrop.top') or ''
    ok(f'the warning names what is replaced and what stays', 'replaced by the plan' in body and '3 milestones and 7 tasks' in body and '2 ideas are added' in body and 'renamed to Clan Cup' in body and 'building, place, notes, links, urgency, and history stay' in body)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    ok('cancelling changes nothing', proj()['todos'] == before['todos'] and proj()['name'] == before['name'])
    pg.click('#planLoad'); pg.wait_for_timeout(300)
    pg.click('.confirm-actions .btn-danger'); pg.wait_for_timeout(500)
    after = proj()
    ok('confirming replaces the name, About, milestones, and tasks', after['name'] == 'Clan Cup' and after['description'].startswith('Clan Cup is a weekly tournament') and [m['name'] for m in after['milestones']] == ['Rules and screens agreed', 'First cup runs on the test server', 'Clan Cup is live'] and len(after['todos']) == 7)
    ok('every task keeps its description, and the due date loads', all(t['description'] for t in after['todos']) and any(t['due'] == '2026-11-15' for t in after['todos']))
    ok('ideas are added to the notes, and the old notes stay', any(n['title'] == 'Idea: a season of cups' for n in after['notes']) and any(n['title'] == 'Leader' for n in after['notes']) and len(after['notes']) == len(before['notes']) + 2)
    ok('the building, place, and urgency stay', after['plot'] == before['plot'] and after['generic'] == before['generic'] and after['urgency']['system'] == 'finish')
    ok('the load is in the activity log', any(e['text'] == 'Loaded a plan: 3 milestones, 7 tasks, 2 ideas' for e in after['activity']))
    ok('the view shows it at once, with What is next on the first task', pg.text_content('#pvTitle') == 'Clan Cup' and 'Write the Clan Cup rules page' in pg.text_content('#pvNextTask'))
    pg.click('.pv-next-row >> text=Copy for Claude'); pg.wait_for_timeout(150)
    clip = js("() => navigator.clipboard.readText()")
    ok('Copy for Claude carries the task description and the About, ready to work on', clip.startswith('# Task: Write the Clan Cup rules page') and 'Done when: the rules page exists' in clip and '## About the project' in clip and 'Clan Cup is a weekly tournament' in clip)
    # the same plan again, from the file button: no duplicate ideas
    pg.click('#pvMore'); pg.click('.pv-menu-item >> text=Load plan or tasks'); pg.wait_for_timeout(300)
    pg.set_input_files('#planFile', str(PLAN)); pg.wait_for_timeout(500)
    ok('choosing the file goes straight to the warning', pg.is_visible('.backdrop.top'))
    pg.click('.confirm-actions .btn-danger'); pg.wait_for_timeout(500)
    ok('loading it again does not duplicate the ideas', len(proj()['notes']) == len(after['notes']) and len(proj()['todos']) == 7)
    # the tool's own export loads into another project: a round trip through Claude
    pg.click('#pvMore')
    with pg.expect_download() as dl:
        pg.click('.pv-menu-item >> text=Export this project')
    exported = pathlib.Path(dl.value.path()).read_text()
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    nc = js("() => DB.projects.find(p => p.name === 'Nullovation City').id")
    js("() => MapView.setCam({ x: 0, y: 230, z: 2 })"); pg.wait_for_timeout(250)
    a = js(f"() => MapView.anchors('{nc}')")
    pg.mouse.click(left + a['topX'], (a['topY'] + a['baseY']) / 2); pg.wait_for_timeout(450)
    pg.click('#enterBtn'); pg.wait_for_timeout(600)
    pg.click('#pvMore'); pg.click('.pv-menu-item >> text=Load plan or tasks'); pg.wait_for_timeout(300)
    pg.fill('#planText', exported); pg.click('#planLoad'); pg.wait_for_timeout(300)
    pg.click('.confirm-actions .btn-danger'); pg.wait_for_timeout(500)
    ncp = js(f"() => JSON.parse(JSON.stringify(DB.projects.find(p => p.id === '{nc}')))")
    ok('an exported project loads into another one, milestones and descriptions intact', len(ncp['milestones']) == 3 and len(ncp['todos']) == 7 and all(t['description'] for t in ncp['todos']))
    # a tasks file adds to a milestone you pick, and changes nothing else
    TASKS = SKILLS / 'nullovation-city' / 'references' / 'example-tasks.json'
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    open_view()
    b4 = proj()
    pg.click('#pvMore'); pg.click('.pv-menu-item >> text=Load plan or tasks'); pg.wait_for_timeout(300)
    pg.fill('#planText', TASKS.read_text()); pg.click('#planLoad'); pg.wait_for_timeout(300)
    ok('a tasks file shows its tasks and a milestone picker, with no warning', pg.is_visible('#planMilestone') and pg.locator('.plan-tasks li').count() == 2 and not pg.is_visible('.backdrop.top'))
    sel = js("() => document.querySelector('#planMilestone').selectedOptions[0].textContent")
    ok(f'the milestone the file names is preselected ({sel})', sel == 'Rules and screens agreed')
    pg.click('#planAdd'); pg.wait_for_timeout(400)
    af = proj()
    ms0 = af['milestones'][0]['id']
    ok('the tasks land at the end of that milestone', [t['text'] for t in af['todos'] if t['milestoneId'] == ms0][-2:] == ['Add a no-show rule to the Clan Cup rules page', 'Ask community to announce the sign-up deadline'])
    ok('nothing else changed', af['description'] == b4['description'] and len(af['milestones']) == len(b4['milestones']) and len(af['todos']) == len(b4['todos']) + 2 and af['notes'] == b4['notes'])
    ok('each added task is in the activity log', sum(1 for e in af['activity'] if e['text'].startswith('Added todo: ')) >= 2)
    import json as _j
    other = _j.dumps({'app': 'nullovation-city', 'kind': 'tasks', 'version': 1, 'milestone': 'Launch week', 'tasks': [{'text': 'Book the launch stream', 'description': 'Book the launch stream slot with community.'}]})
    pg.click('#pvMore'); pg.click('.pv-menu-item >> text=Load plan or tasks'); pg.wait_for_timeout(300)
    pg.fill('#planText', other); pg.click('#planLoad'); pg.wait_for_timeout(300)
    ok('an unknown milestone name is offered as a new milestone', js("() => document.querySelector('#planMilestone').value") == 'new' and 'Launch week' in pg.text_content('#planMilestone'))
    pg.click('#planAdd'); pg.wait_for_timeout(400)
    ok('adding creates it at the end', proj()['milestones'][-1]['name'] == 'Launch week' and proj()['todos'][-1]['text'] == 'Book the launch stream')
    plain = _j.dumps({'app': 'nullovation-city', 'kind': 'tasks', 'version': 1, 'tasks': [{'text': 'Check the crest artwork', 'description': 'Check the winner crest artwork at small sizes.'}]})
    pg.click('#pvMore'); pg.click('.pv-menu-item >> text=Load plan or tasks'); pg.wait_for_timeout(300)
    pg.fill('#planText', plain); pg.click('#planLoad'); pg.wait_for_timeout(300)
    cur = js(f"() => currentGroup(DB.projects.find(p => p.id === '{wz}')).ms.id")
    ok('with no milestone named, the current milestone is preselected', js("() => document.querySelector('#planMilestone').value") == cur)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    ok('closing the picker adds nothing', not any(t['text'] == 'Check the crest artwork' for t in proj()['todos']))
    pg.reload(); pg.wait_for_timeout(1800)
    ok('the loaded plan survives a reload', js(f"() => DB.projects.find(p => p.id === '{wz}').todos.every(t => t.description.length > 40)"))
    b.close()
print(errors or 'no console errors')
